version: '3.8'

services:
  dns-master:
    build:
      context: .
      dockerfile: ../dns.dockerfile
    container_name: manual-dns-master
    hostname: dns-master
    networks:
      dns-net:
        ipv4_address: 10.0.0.13
    expose:
      - "53/tcp"
      - "53/udp"
      - "953/tcp"
    restart: unless-stopped

  dns-slave:
    build:
      context: .
      dockerfile: ../dns.dockerfile
    container_name: manual-dns-slave
    hostname: dns-slave
    networks:
      dns-net:
        ipv4_address: 10.0.0.15
    expose:
      - "53/tcp"
      - "53/udp"
      - "953/tcp"
    restart: unless-stopped

  web-server:
    image: nginx:alpine
    container_name: manual-web-server
    hostname: www.magedu.com
    networks:
      dns-net:
        ipv4_address: 10.0.0.14
    expose:
      - "80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
    restart: unless-stopped

  client:
    build:
      context: .
      dockerfile: ../dns.dockerfile
    container_name: manual-dns-client
    hostname: client
    networks:
      dns-net:
        ipv4_address: 10.0.0.12
    dns:
      - 10.0.0.13
      - 10.0.0.15
    command: tail -f /dev/null
    restart: unless-stopped

networks:
  dns-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1
