version: '3.8'

services:
  ntp-server-1:
    build:
      context: .
      dockerfile: ../ntp.dockerfile
    container_name: auto-ntp-server-1
    hostname: ntp-server-1
    networks:
      ntp-net:
        ipv4_address: 10.0.0.121
    expose:
      - "123/udp"
    volumes:
      - ./configs/chrony-server-1.conf:/etc/chrony.conf:ro
    cap_add:
      - SYS_TIME
      - SYS_NICE
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "chronyc", "tracking"]
      interval: 30s
      timeout: 10s
      retries: 3

  ntp-server-2:
    build:
      context: .
      dockerfile: ../ntp.dockerfile
    container_name: auto-ntp-server-2
    hostname: ntp-server-2
    networks:
      ntp-net:
        ipv4_address: 10.0.0.122
    expose:
      - "123/udp"
    volumes:
      - ./configs/chrony-server-2.conf:/etc/chrony.conf:ro
    cap_add:
      - SYS_TIME
      - SYS_NICE
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "chronyc", "tracking"]
      interval: 30s
      timeout: 10s
      retries: 3

  ntp-server-3:
    build:
      context: .
      dockerfile: ../ntp.dockerfile
    container_name: auto-ntp-server-3
    hostname: ntp-server-3
    networks:
      ntp-net:
        ipv4_address: 10.0.0.123
    expose:
      - "123/udp"
    volumes:
      - ./configs/chrony-server-3.conf:/etc/chrony.conf:ro
    cap_add:
      - SYS_TIME
      - SYS_NICE
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "chronyc", "tracking"]
      interval: 30s
      timeout: 10s
      retries: 3

  client:
    build:
      context: .
      dockerfile: ../ntp.dockerfile
    container_name: auto-ntp-client
    hostname: client
    networks:
      ntp-net:
        ipv4_address: 10.0.0.124
    volumes:
      - ./configs/chrony-client.conf:/etc/chrony.conf:ro
    cap_add:
      - SYS_TIME
    depends_on:
      ntp-server-1:
        condition: service_healthy
      ntp-server-2:
        condition: service_healthy
      ntp-server-3:
        condition: service_healthy
    restart: unless-stopped

networks:
  ntp-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1
